### ISSUE TITLE
Self-hosted: Events do not appear in funnel list

### ISSUE THREAD

**Issue by dubemarcantoine** [Swetrix/swetrix-fe#427]
Hi,
When trying to create a funnel, events do not appear in the funnel list. My installation is on Kubernetes. 

I tried with Docker compose provided and got the same error:
![Screenshot from 2024-06-08 10-12-17](https://github.com/Swetrix/swetrix-fe/assets/11211814/ba683c3d-1e60-4be8-bd97-15a154d25acd)

Error:
```json
{"message":"The provided type (ev) is incorrect","error":"Unprocessable Entity","statusCode":422}
```

docker-compose (essentially the one provided on your self-hosted docs):
```yaml
version: '3.9'
services:
  # This is the frontend, you can remove it if you want
  swetrix:
    image: swetrix/swetrix-fe:v3.0.0
    restart: always
    depends_on:
      - swetrix-api
    ports:
      - '80:3000'
    environment:
      - API_URL=http://localhost:8080/
      - SELFHOSTED=true

  # This is the analytics API
  swetrix-api:
    image: swetrix/swetrix-api:v3.0.0
    restart: always
    container_name: swetrix-api
    ports:
      - '8080:5005'
    environment:
      - JWT_ACCESS_TOKEN_SECRET=jwt-access-token-secret
      - JWT_REFRESH_TOKEN_SECRET=jwt-refresh-token-secret
      - REDIS_HOST=redis
      - CLICKHOUSE_HOST=http://clickhouse
      - API_ORIGINS=
      - EMAIL=test@test.com
      - PASSWORD=12345678
      - API_KEY=
      - CLOUDFLARE_PROXY_ENABLED=false
    links:
      - 'redis'
      - 'clickhouse'
    depends_on:
      - 'redis'
      - 'clickhouse'
  redis:
    image: redis:7.2-alpine
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=
    ports:
      - 6379:6379
    volumes:
      - '/opt/redis-volume:/data'
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DATABASE=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_PASSWORD=
    ports:
      - 8123:8123
    restart: always
    volumes:
      - swetrix-events-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  swetrix-events-data:
    driver: local
```

Thanks for your help!
